site_front_end_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiteFrontEndBundle:Default:index }

home_page:
    path: /
    defaults: {_controller: SiteFrontEndBundle:Default:home }
    
users_page:
    path: /users
    defaults: {_controller: SiteFrontEndBundle:Default:users }
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin