site_front_end_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiteFrontEndBundle:Default:index }

home_page:
    path: /{page}    
    defaults: {_controller: SiteFrontEndBundle:Default:home,page : 1}
    requirements:
        page: \d+
    
users:
    path: /users
    defaults: {_controller: SiteFrontEndBundle:Default:users}
    
users_page:
    path: /users/{slug}
    defaults: {_controller: SiteFrontEndBundle:Default:users}
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin    
