site_front_end_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiteFrontEndBundle:Default:index }

home_page:
    path: /{page}    
    defaults: {_controller: SiteFrontEndBundle:Default:home,page : 1}
    requirements:
        page: \d+
    
users:
    path: /users
    defaults: {_controller: SiteFrontEndBundle:Default:users}
    
news:
    path: /news
    defaults: {_controller: SiteFrontEndBundle:Default:news}

newsget:
    path: /newsget/{post}
    defaults: {_controller: SiteFrontEndBundle:Default:news}    
    
users_page:
    path: /users/{slug}
    defaults: {_controller: SiteFrontEndBundle:Default:users}    
    
getpostbycat:
    path: /cat/{slug}
    defaults: {_controller: SiteFrontEndBundle:Default:postsByCat}