Site\BackEndBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: Site\BackEndBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
        title:
            type: string
            length: 255
        autor:
            type: string
            length: 255
        content:
            type: text
        created:
            type: datetime
        preview:
            type: string
            length: 255
    manyToMany:
        tags:
            targetEntity: Tags
            inversedBy: post
            joinTable:
                name: tags_post
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: posts
            joinColumn: 
                name: cat_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
