services:
#    site_back_end.example:
#        class: Site\BackEndBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
# Acme/DemoBundle/Resources/config/admin.yml
    sonata.admin.post:
        class: Site\BackEndBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Записи" }
        arguments:
            - ~
            - Site\BackEndBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
            
    sonata.admin.tags:
        class: Site\BackEndBundle\Admin\TagsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Тэги", label: "Записи" }
        arguments:
            - ~
            - Site\BackEndBundle\Entity\Tags
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
            
    sonata.admin.category:
        class: Site\BackEndBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "категории", label: "Записи" }
        arguments:
            - ~
            - Site\BackEndBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
    
    tags_manager:
        class: Site\BackEndBundle\Service\TagsManager
        arguments:
            - @service_container